name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Node Setup
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: npm run build
      run: |
        cd app
        npm i @angular/cli && npm i
        npm run build
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag smhagit/website-frontend:latest
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push the Docker image
      run: docker push smhagit/website-frontend
